### ISSUE TITLE
TypeError with click >=8.4 when pyproject.toml sets line-length

### ISSUE THREAD

**Issue by bboe** [LilSpazJoekp/docstrfmt#207]
## Repro

```console
$ printf '[tool.docstrfmt]\nline-length = 100\n' > pyproject.toml
$ printf 'Title\n=====\n\nText.\n' > t.rst
$ docstrfmt -p pyproject.toml t.rst
...
  File ".../click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: main() missing 1 required positional argument: 'line_length'
```

## Version matrix (docstrfmt 2.0.2)

| click | `-p pyproject.toml` w/ `line-length` | notes |
| --- | --- | --- |
| 8.3.3 | ✅ works | |
| 8.4.0 | ❌ TypeError | |
| 8.4.1 | ❌ TypeError | |

Additional observations:

- Auto-discovery (no explicit `-p`, same pyproject.toml in cwd) works on 8.4.x — only an explicitly passed `-p` fails.
- A config without `line-length` (e.g. only `extend_exclude`) works on 8.4.x.
- So the trigger is: explicit `-p` + a config key that shadows a CLI option whose callback pops it (`_resolve_length` does `context.params.pop("line_length", None)`).

## Likely cause

`_parse_pyproject_config` injects config keys into both `context.params` and `context.default_map`, and `_resolve_length` later pops `line_length` back out of `context.params`, relying on click to re-assign the callback's return value. click 8.4 changed parameter processing internals, and with an explicitly provided `-p` the pop is no longer followed by a re-assignment, so `line_length` is absent from `ctx.params` at invoke time.

## Context

This is why praw-dev repos currently pin `additional_dependencies: [click<8.4]` on the pre-commit hook — we'd love to drop that guard.

Happy to take a stab at a PR if useful.
